### ISSUE TITLE
Colored Noise image artefacts 

### ISSUE THREAD

**Issue by jac0b-w** [mazznoer/colorgrad-rs#10]
When generating a [colored noise](https://github.com/mazznoer/colorgrad-rs#colored-noise) image some artefacts appear around the edges between colors. As shown below:

![image](https://github.com/mazznoer/colorgrad-rs/assets/51512690/8c094f59-7be6-4a38-a148-27d412fbba10)

Is there any way to prevent these from forming? (They are also present in the README example if you look carefully)

[Here's my current code generating the noise (AlbumPaper).](https://github.com/jac0b-w/AlbumPaper/blob/master/src/noise.rs#L15-L24) Thanks for any help :)

**Comment by mazznoer** [comment]
```rust
    let grad = colorgrad::CustomGradient::new()
        .colors(&[
            Color::from_rgba8(color1[0], color1[1], color1[2], 255),
            Color::from_rgba8(color2[0], color2[1], color2[2], 255),
        ])
        .build()
        .unwrap()
        .sharp(3, 0.1); // 👈 try 0.0 instead of 0.1
```

**Comment by jac0b-w** [comment]
I don't think lowering this to `0.0` is actually preventing the artifacting rather than just making it less noticeable (I was using `0.1` as a sort of antialiasing). Thinking about it this is almost certainly due to the noise being generated incorrectly rather anything to do with colorgrad so I'll close this issue :)
