### ISSUE TITLE
Make gradient send?

### ISSUE THREAD

**Issue by jackyarndley** [mazznoer/colorgrad-rs#2]
Are you able to change `Gradient` to be `Send`? I think changing the definition to:

`gradient: Box<dyn GradientBase + Send>`

should work (at least it does on my end).

**Comment by mazznoer** [comment]
I am new to Rust, so please elaborate. What problem does it solved?

**Comment by jackyarndley** [comment]
Adding the `Send` trait to the definition indicates that this type is safe to send it to another thread. If I wanted to use the gradient from more than one thread this is needed.

**Comment by mazznoer** [comment]
Feel free to submit a PR. I'll merged it.
