### ISSUE TITLE
Radial gradients?

### ISSUE THREAD

**Issue by wez** [mazznoer/colorgrad-rs#4]
This looks like a really nice crate!
Any recommendations on how to apply this to generate radial gradients?

**Comment by mazznoer** [comment]
This links might help you

* https://github.com/fogleman/gg/blob/master/gradient.go#L87
* https://stackoverflow.com/questions/3009754/algorithm-to-generate-radial-gradient

**Comment by wez** [comment]
Thanks for this!
colorgrad-powered gradients are now part of WezTerm and available in nightly builds:
https://wezfurlong.org/wezterm/config/lua/config/window_background_gradient.html
