### ISSUE TITLE
Plans for v0.7.0

### ISSUE THREAD

**Issue by mazznoer** [mazznoer/colorgrad-rs#6]
+ [x] `f64` -> `f32`.
+ [x] `LinearGradient`, `CatmullRomGradient`, `BasisGradient`, etc will be return directly. No more `Box`.

**Comment by Atif-Mahmud** [comment]
Hi! Any updates one this? Willing to help out, perhaps some notes / things to keep in mind?

**Comment by ahcm** [comment]
Looking forward to 0.7.0.

**Comment by murl-digital** [comment]
Hi, it seems like 0.7's feature complete, could it be published? I'm using it for my projects and would rather not have to rely on the git repository

**Comment by mazznoer** [comment]
Version 0.7.0 is now available at crates.io
