### ISSUE TITLE
Custom domains for presets

### ISSUE THREAD

**Issue by HHogg** [mazznoer/colorgrad-rs#7]
👋  Thanks for the library. 

Have you thought about providing custom domains for the presets, similar to how d3-color does it, unless there's a different way of doing this with colorgrad-rs? Something along the lines of... 

```rs
colorgrad::spectral().domain(my_domain_min, my_domain_max)
```

**Comment by mazznoer** [comment]
You can use this function to do that.

```rust
// map t from range [a, b] to range [0, 1]
fn norm(t: f64, a: f64, b: f64) -> f64
{
    (t-a) * (1.0 / (b-a))
}

let grad = colorgrad::rainbow();

// domain is from -100 to 100.
grad.at(norm(0.0, -100.0, 100.0));

// domain is from 0 to 50.
grad.at(norm(0.0, 0.0, 50.0));
```

**Comment by HHogg** [comment]
Thanks for the response @mazznoer. 

As there is a domain that is used internally, I wonder if you'd be open to an API to allow it to be configured. It would be helpful from an API perspective, where you have a gradient stored and used in lots of place. The current options as you say is to either interpolate the values on each call, or create a proxy to it.
